api_version = "2025-01"

[[extensions]]
name = "catalogue-badge"
handle = "catalogue-badge"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
api_access = true

[[extensions.metafields]]
namespace = "custom"
key = "tier"